version: "3.8"
services:
  zookeeper:
    image: zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-server
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  redis-server1:
    image: redis:latest
    container_name: redis-server1
    ports:
      - "6379:6379"
  redis-server2:
    image: redis:latest
    container_name: redis-server2
    ports:
      - "6380:6379"

  kafka-topics-creator:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-topics-creator
    depends_on:
      - kafka
    entrypoint: >
      bash -c "
      kafka-topics --create --topic notification-topic --bootstrap-server kafka-server:9092 --partitions 3 --replication-factor 1 &&
      kafka-topics --create --topic email-topic --bootstrap-server kafka-server:9092 --partitions 3 --replication-factor 1
      "
  # schema-registry:
  #   image: confluentinc/cp-schema-registry:7.0.0
  #   depends_on: [kafka]
  #   ports: ["8081:8081"]
  #   environment:
  #     SCHEMA_REGISTRY_HOST_NAME: schema-registry
  #     SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
